baseURL = "https://chilblane.netlify.com/"
languageCode = "en-us"
title = "Chilblane"
theme = "chilblane"

[params]
    homeHeroHeadline = "Daniel Singer"
    homeHeroText = "Product designer and UI engineer"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 2
