baseURL = "https://www.chilblane.com/"
languageCode = "en-us"
title = "Chilblane.com"
theme = "chilblane"
googleAnalytics = "UA-65603184-1"

[params]
    description = "UX designer and UI engineer based in Phoenix, Arizona."
    homeHeroHeadline = "Daniel Singer"
    homeHeroText = "Product designer and UI engineer"


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 2
