baseURL = "https://www.chilblane.com/"
languageCode = "en-us"
title = "Daniel Singer | Product designer & design technologist"
theme = ["chilblane", "hugo-shortcode-gallery"]
googleAnalytics = "UA-65603184-1"
timeout = 60000

[params]
    description = "Daniel Singer is a product designer and design technologist based in Phoenix, Arizona."
    navTitle = "Daniel Singer"
    navSubTitle = "Chilblane"
    images = ["og-image.jpg"]
    galleryLoadJQuery = true
    gallerySortOrder = "asc"
    galleryPreviewType="blur"
    galleryEmbedPreview="true"
    galleryMargins="8"


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Work"
        url = "/work/"
        weight = 2
    [[menu.main]]
        name = "Blog"
        url = "/blog/"
        weight = 3
