baseURL = "https://www.chilblane.com/"
languageCode = "en-us"
title = "Chilblane.com"
theme = "chilblane"
googleAnalytics = "UA-65603184-1"
timeout = 60000

[params]
    description = "Product designer and design technologist based in Phoenix, Arizona."
    navTitle = "Daniel Singer"
    navSubTitle = "Chilblane"


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Work"
        url = "/work/"
        weight = 2
    [[menu.main]]
        name = "Blog"
        url = "/blog/"
        weight = 3
