baseURL = "https://www.chilblane.com/"
languageCode = "en-us"
title = "Chilblane.com"
theme = "chilblane"
googleAnalytics = "UA-65603184-1"
timeout = 60000

[params]
    description = "UX designer and UI engineer based in Phoenix, Arizona."
    homeHeroHeadline = "Chilblane"


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Articles"
        url = "/articles/"
        weight = 2
